"""Independent native geometry/pixel checks for display-equation fixture 72.

The oracle uses the written 24/64px rhythm, source-owned AT-SPI nodes and
actual glyph ink, not a golden regenerated by the implementation under test.
"""
import argparse
import json
from pathlib import Path

from PIL import Image


def check(prefix):
    source = json.loads(prefix.with_suffix('.source.json').read_text())
    tree = json.loads(prefix.with_suffix('.active-atspi.json').read_text())
    assert source['passes'] and source['source_unchanged']
    assert source['binary_sha256'] == tree['binary_sha256']
    image = Image.open(prefix.with_suffix('.png')).convert('RGB')
    nodes = tree['nodes']
    zoom = 1 + source['zoom_steps'] / 10
    document_index = next(i for i, n in enumerate(nodes) if n['role'] == 'document frame')
    roots = [n for n in nodes if n['parent'] == document_index]
    equations = [n for n in roots if n['role'] == 'math']
    assert len(equations) == 6
    assert [n['name'].strip().startswith(s) for n, s in zip(equations, (
        'y = ax + b', 'x = \\frac', 'A = \\begin{pmatrix}', '\\sum', 'a_{1}', '\\frac{'
    ))] == [True] * 6
    assert all(n.get('attributes', {}).get('tag') == 'math' for n in equations[:5])
    assert equations[-1].get('attributes', {}).get('tag') != 'math', 'Invalid input must not fabricate MathML'

    def near(actual, expected, tolerance=1.2):
        assert abs(actual - expected) <= tolerance, (actual, expected)

    inspected = []
    for equation in equations[:5]:
        b = equation['bounds']
        index = roots.index(equation)
        before, after = roots[index - 1], roots[index + 1]
        p, n = before['bounds'], after['bounds']
        near(b['y'] - p['y'] - p['height'], 24 * zoom)
        near(n['y'] - b['y'] - b['height'], (64 if after['role'] == 'heading' else 24) * zoom)
        # Compact formulas share their adjacent prose measure; the long sum
        # can break out. No visible source row or source-panel tint is valid.
        compact = equation is not equations[4]
        if compact and before['role'] == 'paragraph':
            near(b['width'], p['width'])
        if b['y'] < 52 or b['y'] + b['height'] >= image.height - 30:
            continue
        x, y, w, h = (round(b[k]) for k in ('x', 'y', 'width', 'height'))
        assert image.getpixel((x + 2, y + 2)) == (250, 249, 246)
        assert image.getpixel((x + w - 3, y + 2)) == (250, 249, 246)
        if compact:
            ink = image.crop((x, y, x + w, y + h)).convert('L').point(lambda p: 255 if p < 160 else 0)
            bounds = ink.getbbox()
            assert bounds is not None, equation['name']
            near((bounds[0] + bounds[2]) / 2, (w - 8 * zoom) / 2, 4 * zoom)
            assert bounds[3] - bounds[1] > .5 * h, (equation['name'], bounds, h)
        inspected.append(equation['name'].strip())
    assert inspected, 'No complete visible equation was checked'
    return dict(passes=True, binary_sha256=source['binary_sha256'],
                fixture_sha256=source['original_sha256'], zoom=zoom,
                gap=24 * zoom, section_gap=64 * zoom,
                rendered_equations=5, recoverable_sources=1, pixel_equations=inspected)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('prefix', nargs='+', type=Path)
    results = {str(p): check(p) for p in parser.parse_args().prefix}
    assert len({r['binary_sha256'] for r in results.values()}) == 1
    for prefix, result in results.items():
        Path(prefix).with_suffix('.pixels.json').write_text(json.dumps(result, indent=2) + '\n')
    print(json.dumps(results, indent=2))


if __name__ == '__main__':
    main()
