"""Regression oracles for native layout evidence; no app or display required."""
import copy
import hashlib
import importlib.util
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

spec = importlib.util.spec_from_file_location("capture_layout", Path(__file__).with_name("capture-layout.py"))
capture = importlib.util.module_from_spec(spec)
spec.loader.exec_module(capture)


class GeometryEvidenceTests(unittest.TestCase):
    def test_generated_accessibility_root_count_matches_fixture_only_complete_sections(self):
        source = (
            b"---\ntitle: fixture\n---\n\n# Title\n\nIntro\n\n"
            b"## Field section 1\nbody\n## Field section 2\nbody\n"
            b"## Field section incomplete\n<!-- padding:x -->\n"
        )
        self.assertEqual(capture.generated_accessible_root_count(source), 70)

    def test_bounded_activation_sampling_requires_generated_active_atspi_without_sweep(self):
        for options in (
            [],
            ["--atspi-active"],
            ["--generated-bytes", "1048576"],
            ["--atspi-active", "--generated-bytes", "1048576",
             "--perf-seconds", "1", "--perf-sweep-seconds", "1",
             "--perf-input", "continuous"],
        ):
            command = [sys.executable, str(Path(capture.__file__)),
                       "--atspi-activation-sample", *options]
            result = subprocess.run(
                command, capture_output=True, text=True, timeout=5,
            )
            self.assertEqual(result.returncode, 2)
            self.assertIn("requires generated bytes and active AT without a full sweep", result.stderr)

    def test_warmed_sweep_requires_a_full_document_sweep(self):
        result = subprocess.run([sys.executable, str(Path(capture.__file__)), "--perf-warm-sweep"],
                                capture_output=True, text=True, timeout=5)
        self.assertEqual(result.returncode, 2)
        self.assertIn("--perf-warm-sweep requires --perf-sweep-seconds", result.stderr)

    def test_continued_resize_edit_requires_exact_record_editing_scenario(self):
        for options in ([], ["--resize-check", "reading", "--fixture", "122-paired-records.md", "--resize-target", "record-header"],
                        ["--resize-check", "editing", "--fixture", "01-field-notes.md"]):
            result = subprocess.run([sys.executable, str(Path(capture.__file__)),
                                     "--resize-continue-edit", *options],
                                    capture_output=True, text=True, timeout=5)
            self.assertEqual(result.returncode, 2)
            self.assertIn("--resize-continue-edit requires fixture122", result.stderr)

    def test_timeline_resize_requires_whole_fixture_explicit_target_and_supported_zoom(self):
        for options in (["--resize-target", "timeline-code"],
                        ["--resize-check", "reading", "--fixture", "01-field-notes.md", "--resize-target", "timeline-body"],
                        ["--resize-check", "reading", "--fixture", "119-rich-timelines.md"],
                        ["--resize-check", "reading", "--fixture", "119-rich-timelines.md", "--resize-target", "timeline-nested", "--zoom-steps", "2"]):
            result = subprocess.run([sys.executable, str(Path(capture.__file__)), *options],
                                    capture_output=True, text=True, timeout=5)
            self.assertEqual(result.returncode, 2)
            self.assertIn("timeline resize targets require fixture119", result.stderr)

    def test_specification_resize_requires_its_whole_fixture_and_supported_zoom(self):
        for options in ([], ["--resize-check", "reading", "--fixture", "01-field-notes.md"],
                        ["--resize-check", "reading", "--fixture", "03-technical-reference.md", "--zoom-steps", "2"]):
            result = subprocess.run([sys.executable, str(Path(capture.__file__)),
                                     "--resize-target", "specification-code", *options],
                                    capture_output=True, text=True, timeout=5)
            self.assertEqual(result.returncode, 2)
            self.assertIn("specification resize targets require fixture03", result.stderr)

    def test_selection_before_zoom_requires_an_actual_zoom(self):
        result = subprocess.run(
            [sys.executable, str(Path(capture.__file__)), "--select-before-zoom"],
            capture_output=True, text=True, timeout=5,
        )
        self.assertEqual(result.returncode, 2)
        self.assertIn("requires nonzero --zoom-steps", result.stderr)

    def test_holdout_origin_drift_does_not_masquerade_as_private_copy_corruption(self):
        with tempfile.TemporaryDirectory() as temporary:
            source = Path(temporary) / "original.md"
            staged = b"# Exact source\r\n\r\nKeep trailing spaces.  \r\n"
            source.write_bytes(staged)
            evidence = capture.source_origin_evidence(source, staged)
            self.assertEqual(evidence["state_at_check"], "unchanged")
            self.assertEqual(evidence["path"], str(source))
            self.assertEqual(evidence["staged_sha256"], hashlib.sha256(staged).hexdigest())
            self.assertEqual(evidence["current_sha256"], evidence["staged_sha256"])
            self.assertEqual(evidence["resource_scope"], "selected_markdown_only")

            changed = b"# Externally revised source\n"
            source.write_bytes(changed)
            drift = capture.source_origin_evidence(source, staged)
            self.assertEqual(drift["state_at_check"], "changed")
            self.assertEqual(drift["current_sha256"], hashlib.sha256(changed).hexdigest())
            self.assertEqual(drift["staged_sha256"], evidence["staged_sha256"])
            self.assertEqual(source.read_bytes(), changed)
            self.assertNotIn("passes", drift)

            source.unlink()
            missing = capture.source_origin_evidence(source, staged)
            self.assertEqual(missing["state_at_check"], "unavailable")
            self.assertEqual(missing["error_type"], "FileNotFoundError")
            self.assertIsNone(missing["current_sha256"])
            self.assertEqual(missing["staged_sha256"], evidence["staged_sha256"])
            self.assertFalse(source.exists())

    def test_source_holdout_is_exact_and_edits_cannot_reach_original(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            original = root / "original.md"
            content = b"# Exact holdout\r\n\r\nKeep **syntax** and trailing spaces.  \r\n"
            original.write_bytes(content)
            private = root / "fixtures"
            private.mkdir()
            relative = capture.stage_source_document(original, private)
            staged = private / relative
            self.assertTrue(staged.resolve().is_relative_to(private.resolve()))
            self.assertEqual(staged.read_bytes(), content)
            self.assertNotEqual(staged.resolve(), original.resolve())
            staged.write_bytes(b"edited private copy")
            self.assertEqual(original.read_bytes(), content)

    def test_explicit_resource_directories_preserve_authored_relative_paths(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            source = root / "project/example/reference.md"
            source.parent.mkdir(parents=True)
            source.write_bytes(b"![figure](../assets/figure.svg)\n")
            assets = source.parent.parent / "assets"
            assets.mkdir()
            (assets / "figure.svg").write_bytes(b"<svg/>")
            private = root / "private"
            private.mkdir()
            staged = private / capture.stage_source_document(source, private)
            evidence = capture.stage_source_resources(source, staged, private, [assets])
            copied = staged.parent / "../assets/figure.svg"
            self.assertEqual(copied.read_bytes(), b"<svg/>")
            self.assertEqual(evidence[0]["relative_path"], "../assets")
            copied.write_bytes(b"changed private resource")
            self.assertEqual((assets / "figure.svg").read_bytes(), b"<svg/>")
            self.assertEqual(staged.read_bytes(), source.read_bytes())

    def test_source_resources_cannot_escape_private_root(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            source = root / "a/b/c/reference.md"
            source.parent.mkdir(parents=True)
            source.write_bytes(b"# Reference")
            assets = root / "assets"
            assets.mkdir()
            private = root / "private"
            private.mkdir()
            staged = private / capture.stage_source_document(source, private)
            with self.assertRaisesRegex(ValueError, "escapes"):
                capture.stage_source_resources(source, staged, private, [assets])

    def test_fixture_paths_cannot_escape_private_session(self):
        for fixture in ("/tmp/original.md", "../../README.md"):
            result = subprocess.run([sys.executable, str(Path(capture.__file__)),
                                     "--fixture", fixture], capture_output=True, text=True, timeout=5)
            self.assertEqual(result.returncode, 2)
            self.assertIn("must stay inside the private fixture directory", result.stderr)

    def test_resize_burst_requires_native_scenario_and_trace(self):
        for options in ([], ["--resize-check", "reading"]):
            command = [sys.executable, str(Path(capture.__file__)),
                       "--fixture", "79-technical-sections.md", "--resize-burst", *options]
            result = subprocess.run(command, capture_output=True, text=True, timeout=5)
            self.assertEqual(result.returncode, 2)
            self.assertIn("--resize-burst requires --resize-check and --layout-trace", result.stderr)

    def test_desktop_resize_cannot_claim_maximized_appearance_pixels(self):
        for mode in ("--resize-check", "--boundary-check", "--font-reflow-check"):
            command = [sys.executable, str(Path(capture.__file__)), "--appearance", "dark", mode]
            if mode == "--resize-check":
                command.append("reading")
            result = subprocess.run(command, capture_output=True, text=True, timeout=5)
            self.assertEqual(result.returncode, 2)
            self.assertIn("appearance pixel checks require a maximized kiosk window", result.stderr)

    def test_startup_requires_latest_usable_publication_and_resolved_images(self):
        ready = capture.measured_startup_ready
        report = dict(committed=True, scope="whole_document", canvas_width=1280,
                      planner_failed=False, unresolved_image_dimensions=0)
        self.assertFalse(ready([], 1280))
        self.assertFalse(ready([dict(report, committed=False)], 1280))
        self.assertTrue(ready([report], 1280))
        for invalid in (dict(report, canvas_width=770), dict(report, planner_failed=True),
                        dict(report, unresolved_image_dimensions=1), dict(report, scope="viewport")):
            self.assertFalse(ready([report, invalid], 1280))
        self.assertTrue(ready([report, dict(report, committed=False, canvas_width=770)], 1280))
        self.assertFalse(ready([dict(committed=True, canvas_width=1280)], 1280))

    def test_definition_startup_requires_both_rails_and_numbered_composition(self):
        from PIL import Image
        plain = Image.new("RGB", (1600, 1200), (250, 249, 246))
        self.assertFalse(capture.check_idle_definition_frames([plain, plain])["passes"])
        measured = plain.copy()
        for x, y in [(276, 334), (388, 334), (276, 422), (388, 422)]:
            measured.paste((54, 66, 62), (x, y, x + 20, y + 5))
        self.assertFalse(capture.check_idle_definition_frames([measured, measured])["passes"])
        measured.paste((63, 98, 71), (735, 600, 740, 610))
        hovered = measured.copy()
        hovered.putpixel((800, 350), (0, 0, 0))
        self.assertTrue(capture.check_idle_definition_frames([measured, hovered])["passes"])
        hovered.putpixel((700, 500), (0, 0, 0))
        self.assertFalse(capture.check_idle_definition_frames([measured, hovered])["passes"])

    def test_idle_startup_requires_visible_timeline_and_ignores_only_pointer(self):
        from PIL import Image
        plain = Image.new("RGB", (1150, 880), (250, 249, 246))
        self.assertFalse(capture.check_idle_document_frames([plain, plain])["passes"])
        measured = plain.copy()
        measured.putpixel((206, 74), (63, 98, 71))
        hovered = measured.copy()
        hovered.putpixel((400, 90), (0, 0, 0))
        self.assertTrue(capture.check_idle_document_frames([measured, hovered])["passes"])
        hovered.putpixel((700, 240), (0, 0, 0))
        self.assertFalse(capture.check_idle_document_frames([measured, hovered])["passes"])

    def test_inline_preedit_oracle_requires_exactly_one_inserted_codepoint(self):
        inserted = capture.single_inserted_codepoint
        self.assertEqual(inserted("arrangements", "a´rrangements"), (1, "´"))
        self.assertEqual(inserted("text", "´text"), (0, "´"))
        self.assertEqual(inserted("text", "text´"), (4, "´"))
        self.assertEqual(inserted("emoji", "em🙂oji"), (2, "🙂"))
        self.assertIsNone(inserted("text", "text"))
        self.assertIsNone(inserted("text", "toast"))
        self.assertIsNone(inserted("text", "te´´xt"))

    def test_plain_text_edit_oracle_removes_only_markdown_punctuation_escapes(self):
        unescape = capture.unescape_markdown_punctuation
        self.assertEqual(
            unescape(b"Measured shaping\\, automatic a\xc3\xa9rrangements\\."),
            "Measured shaping, automatic aérrangements.".encode(),
        )
        self.assertEqual(unescape(b"two\\\\slashes"), b"two\\slashes")
        self.assertEqual(unescape(b"leave\\qunknown"), b"leave\\qunknown")

    def test_exact_copy_oracle_requires_markers_and_complete_golden_text(self):
        copied = "alpha\nbeta\ngamma"
        result = capture.check_copied_text(copied, ["alpha", "gamma"], copied)
        self.assertTrue(result["passes"])
        self.assertTrue(result["exact_clipboard"])
        self.assertFalse(capture.check_copied_text(copied, ["gamma", "alpha"], copied)["passes"])
        self.assertFalse(capture.check_copied_text(copied, ["alpha"], copied + "\n")["passes"])
        marker_only = capture.check_copied_text(copied, ["alpha", "gamma"])
        self.assertTrue(marker_only["passes"])
        self.assertIsNone(marker_only["exact_clipboard"])

    def test_source_marker_insertion_includes_both_endpoints(self):
        matches = capture.inserted_marker_matches
        marker = b"Keep original messages"
        original = b"| Evidence retention | " + marker + b". |\n"
        for insertion in [b"x", "é".encode(), b"Carefully "]:
            for offset in [0, 2, len(marker)]:
                with self.subTest(insertion=insertion, offset=offset):
                    changed = marker[:offset] + insertion + marker[offset:]
                    self.assertTrue(matches(original, original.replace(marker, changed), marker, insertion))
        escaped = original.replace(marker, b"Keep xoriginal messages").replace(b".", b"\\.")
        self.assertTrue(matches(original, escaped, marker, b"x"))

    def test_source_marker_insertion_rejects_missing_ambiguous_and_wrong_targets(self):
        matches = capture.inserted_marker_matches
        marker = b"Keep original messages"
        original = b"| Evidence retention | " + marker + b". |\n"
        self.assertFalse(matches(original, original, marker, b"x"))
        self.assertFalse(matches(original, original.replace(b"Evidence", b"xEvidence"), marker, b"x"))
        self.assertFalse(matches(original, original.replace(marker, b"Keep messages"), marker, b"x"))
        self.assertFalse(matches(original, original.replace(marker, b"Other messages"), marker, b"x"))
        self.assertFalse(matches(original + marker, original + b"x" + marker, marker, b"x"))
        self.assertFalse(matches(original, original.replace(marker, b"x" + marker) * 2, marker, b"x"))
        self.assertFalse(matches(original, original, b"absent", b"x"))
        self.assertFalse(matches(original, original, marker, b""))

    def test_selection_keys_release_navigation_and_shift(self):
        self.assertEqual(capture.selection_key_events("alt-enter"),
                         [(56, 1), (28, 1), (28, 0), (56, 0)])
        for name, code in capture.SELECTION_KEY_CODES.items():
            self.assertEqual(capture.selection_key_events(name), [(code, 1), (code, 0)])
            self.assertEqual(capture.selection_key_events("shift-" + name),
                             [(42, 1), (code, 1), (code, 0), (42, 0)])
        for name in ("left", "right"):
            code = capture.SELECTION_KEY_CODES[name]
            self.assertEqual(capture.selection_key_events("ctrl-" + name),
                             [(29, 1), (code, 1), (code, 0), (29, 0)])
            self.assertEqual(capture.selection_key_events("ctrl-shift-" + name),
                             [(29, 1), (42, 1), (code, 1), (code, 0), (42, 0), (29, 0)])

    def report(self, published=False):
        return {
            "explicitly_requested": True, "committed": True, "sequence": 1,
            "anchor_displacement_at_commit_px": 0,
            "stages": [{"name": "geometry_and_rendered_extensions", "measurements": {
                "published_geometry_reuses": int(published),
                "geometry_requests": 0 if published else 1522,
                "geometry_cache_hits": 0 if published else 1522,
                "segments_laid_out": 0, "geometry_cache_evictions": 0,
                "wrap_requests": 0, "shaping_calls": 0,
            }}],
        }

    def test_both_reuse_paths_have_positive_evidence(self):
        for published in (False, True):
            capture.check_cached_geometry([self.report(published)], 1)

    def test_malformed_or_incomplete_reuse_is_rejected(self):
        for published in (False, True):
            good = self.report(published)
            for name, value in (
                ("published_geometry_reuses", 2), ("segments_laid_out", 1),
                ("geometry_cache_evictions", 1), ("wrap_requests", 1),
                ("shaping_calls", 1), ("geometry_cache_hits", 42),
            ):
                with self.subTest(published=published, field=name):
                    bad = copy.deepcopy(good)
                    bad["stages"][0]["measurements"][name] = value
                    with self.assertRaises(RuntimeError):
                        capture.check_cached_geometry([bad], 1)
            for name, value in (("committed", False), ("anchor_displacement_at_commit_px", 2)):
                bad = copy.deepcopy(good)
                bad[name] = value
                with self.assertRaises(RuntimeError):
                    capture.check_cached_geometry([bad], 1)
        empty_work = self.report(True)
        empty_work["stages"][0]["measurements"]["published_geometry_reuses"] = 0
        with self.assertRaises(RuntimeError):
            capture.check_cached_geometry([empty_work], 1)
        with self.assertRaises(RuntimeError):
            capture.check_cached_geometry([], 1)


if __name__ == "__main__":
    unittest.main()
