[book]
authors = ["Tachyon contributors"]
language = "en"
src = "src"
title = "Tachyon User Guide"

[build]
build-dir = "../../target/docs-site"
create-missing = false

[output.html]
git-repository-url = "https://github.com/mendrik-private/tachyon"
site-url = "/tachyon/"
edit-url-template = "https://github.com/mendrik-private/tachyon/edit/main/docs/user-guide/{path}"
additional-css = ["theme/tachyon.css"]
no-section-label = true
preferred-dark-theme = "navy"
